#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const origin = "https://gusdigitalsolutions.com/herphase";
const posts = JSON.parse(await readFile(resolve("scripts/blog-posts.json"), "utf8")).entries;
const esc = (value) => String(value).replace(/[&<>"']/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[character]);
const articleHeader = `<header class="blog-site-header"><a class="blog-brand" href="../../">HerPhase</a><nav class="blog-desktop-nav" aria-label="Primary navigation"><a href="../../">Home</a><a href="../" aria-current="page">Blog</a><a href="../../privacy/">Privacy</a><a href="../../how-it-works/">How It Works</a><a href="../../medical-disclosure/">Medical Disclosure</a></nav><details class="blog-mobile-menu"><summary aria-label="Open navigation">Menu</summary><nav class="blog-mobile-nav" aria-label="Mobile navigation"><a href="../../">Home</a><a href="../" aria-current="page">Blog</a><a href="../../privacy/">Privacy</a><a href="../../how-it-works/">How It Works</a><a href="../../medical-disclosure/">Medical Disclosure</a></nav></details></header>`;
const articleFooter = `<footer class="blog-footer"><nav aria-label="Footer navigation"><a href="../../">Home</a><a href="../">Blog</a><a href="../../privacy/">Privacy</a><a href="../../support/">Support</a><a href="../../medical-disclosure/">Medical Disclosure</a></nav><p>General wellness information only. HerPhase is not medical advice, diagnosis, contraception, or a fertility tool.</p></footer>`;

for (const post of posts) {
  const file = resolve(`blog/${post.slug}/index.html`);
  const old = await readFile(file, "utf8");
  const copy = old.match(/<!-- @article-copy -->([\s\S]*?)<!-- @\/article-copy -->/)?.[1]?.trim()
    ?? old.match(/<h1[^>]*>[\s\S]*?<\/h1>([\s\S]*?)<\/main>/i)?.[1]?.trim();
  if (!copy) throw new Error(`${post.slug}: could not preserve article copy`);
  const canonical = `${origin}/blog/${post.slug}/`;
  const imageUrl = `${origin}${post.image}`;
  const schema = { "@context":"https://schema.org", "@type":"BlogPosting", headline:post.title, description:post.description, image:{"@type":"ImageObject",url:imageUrl,width:1200,height:630}, datePublished:post.published, dateModified:post.updated, author:{"@type":"Organization",name:"HerPhase"}, publisher:{"@type":"Organization",name:"HerPhase",url:`${origin}/`}, mainEntityOfPage:{"@type":"WebPage","@id":canonical}, url:canonical, inLanguage:"en-US" };
  const related = posts.filter((candidate) => candidate.slug !== post.slug).map((candidate) => `<li><a href="../${candidate.slug}/">${esc(candidate.title)}</a></li>`).join("");
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex, follow"><title>${esc(post.title)} | HerPhase</title><meta name="description" content="${esc(post.description)}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="article"><meta property="og:url" content="${canonical}"><meta property="og:title" content="${esc(post.title)}"><meta property="og:description" content="${esc(post.description)}"><meta property="og:image" content="${imageUrl}"><meta property="og:image:alt" content="${esc(post.imageAlt)}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${imageUrl}"><meta name="twitter:image:alt" content="${esc(post.imageAlt)}"><link rel="stylesheet" href="../../assets/styles.css"><script type="application/ld+json">${JSON.stringify(schema).replaceAll("<","\\u003c")}</script></head><body>${articleHeader}<main class="blog-article"><nav class="blog-breadcrumb" aria-label="Breadcrumb"><a href="../../">Home</a><span>/</span><a href="../">Blog</a><span>/</span><span aria-current="page">${esc(post.title)}</span></nav><a class="blog-back" href="../">← Back to Blog</a><p class="eyebrow">${esc(post.eyebrow)}</p><h1>${esc(post.title)}</h1><p class="blog-updated">By HerPhase · Updated <time datetime="${post.updated}">August 8, 2026</time></p><picture class="blog-cover"><source srcset="../../assets/blog/${post.slug}-1200x630.webp" type="image/webp"><img src="../../assets/blog/${post.slug}-1200x630.png" alt="${esc(post.imageAlt)}" width="1200" height="630" loading="eager" fetchpriority="high" decoding="async" sizes="(min-width:760px) 760px, 100vw"></picture><div class="article-copy"><!-- @article-copy -->${copy}<!-- @/article-copy --></div><aside class="blog-related"><h2>Related Articles</h2><ul>${related}</ul></aside></main>${articleFooter}</body></html>\n`;
  await writeFile(file, html);
}

const lead = posts[0];
const cards = posts.map((post) => `<a class="blog-card" href="${post.slug}/"><picture><source srcset="../assets/blog/${post.slug}-1200x630.webp" type="image/webp"><img src="../assets/blog/${post.slug}-1200x630.png" alt="${esc(post.imageAlt)}" width="1200" height="630" loading="lazy" decoding="async" sizes="(min-width:800px) 460px, 100vw"></picture><div class="blog-card-copy"><h2>${esc(post.title)}</h2><p>${esc(post.description)}</p></div></a>`).join("");
const blogSchema = { "@context":"https://schema.org", "@type":"Blog", name:"HerPhase Blog", url:`${origin}/blog/`, blogPost:posts.map((post) => ({"@type":"BlogPosting",headline:post.title,url:`${origin}/blog/${post.slug}/`,image:{"@type":"ImageObject",url:`${origin}${post.image}`,width:1200,height:630},datePublished:post.published,dateModified:post.updated})) };
const indexHeader = `<header class="blog-site-header"><a class="blog-brand" href="../">HerPhase</a><nav class="blog-desktop-nav" aria-label="Primary navigation"><a href="../">Home</a><a href="./" aria-current="page">Blog</a><a href="../privacy/">Privacy</a><a href="../how-it-works/">How It Works</a><a href="../medical-disclosure/">Medical Disclosure</a></nav><details class="blog-mobile-menu"><summary aria-label="Open navigation">Menu</summary><nav class="blog-mobile-nav" aria-label="Mobile navigation"><a href="../">Home</a><a href="./" aria-current="page">Blog</a><a href="../privacy/">Privacy</a><a href="../how-it-works/">How It Works</a></nav></details></header>`;
const indexFooter = `<footer class="blog-footer"><nav aria-label="Footer navigation"><a href="../">Home</a><a href="./">Blog</a><a href="../privacy/">Privacy</a><a href="../support/">Support</a><a href="../medical-disclosure/">Medical Disclosure</a></nav><p>General wellness information only. HerPhase is not medical advice, diagnosis, contraception, or a fertility tool.</p></footer>`;
const index = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex, follow"><title>Cycle Tracking Blog | HerPhase</title><meta name="description" content="Practical guides to tracking irregular cycles, PMS patterns, and period-app privacy without treating estimates as diagnosis or fertility guidance."><link rel="canonical" href="${origin}/blog/"><meta property="og:type" content="website"><meta property="og:url" content="${origin}/blog/"><meta property="og:title" content="Cycle Tracking Blog | HerPhase"><meta property="og:image" content="${origin}${lead.image}"><meta property="og:image:alt" content="${esc(lead.imageAlt)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${origin}${lead.image}"><meta name="twitter:image:alt" content="${esc(lead.imageAlt)}"><link rel="stylesheet" href="../assets/styles.css"><script type="application/ld+json">${JSON.stringify(blogSchema).replaceAll("<","\\u003c")}</script></head><body>${indexHeader}<main class="blog-index"><nav class="blog-breadcrumb" aria-label="Breadcrumb"><a href="../">Home</a><span>/</span><span aria-current="page">Blog</span></nav><p class="eyebrow">Cycle tracking, patterns, and privacy</p><h1>HerPhase Blog</h1><p class="lede">Clear, source-linked wellness education. HerPhase provides logged-cycle estimates and planning context—not diagnosis, contraception, or medically precise fertility prediction.</p><section class="blog-grid" aria-label="Articles">${cards}</section></main>${indexFooter}</body></html>\n`;
await writeFile(resolve("blog/index.html"), index);
await writeFile(resolve("sitemap.xml"), '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"></urlset>\n');
console.log(`Built ${posts.length} migration-held HerPhase articles and an empty destination sitemap.`);
